### ISSUE TITLE
SUMMARY_REPORT.md misstates its own run's numbers and violates its Confirmed-table eligibility — the source population feeds it wrong values and the prompt asks for fields that don't exist

### ISSUE THREAD

**Issue by gadievron** [knostic/OpenAnt#535]
SUMMARY_REPORT.md misstates its own run's numbers and violates its Confirmed-table eligibility — the source population feeds it wrong values and the prompt asks for fields that don't exist

From the 2026-09-07 monitored end-to-end run of the scan pipeline; re-derived from source at current master (ec6b063); pre-existing on master, not a regression from #526-#531.

## The claim

Three layers contribute, and a fix that only renders tables deterministically would preserve the misstatements:

**(a) Source-side population.** `core/reporter.py:770` computes `"units_analyzed": total_units - metrics.get("errors", 0)` — an errors-silent subtraction that produced `119` where the analyze stage recorded `analyzed: 120`, and that feeds every downstream count rendering.

**(b) The prompt asks for values the pipeline does not supply.** `report/prompts/summary.txt:32` renders "Parsed: {n} functions from {n} files" — no such fields exist in `pipeline_output`; the same run rendered "120 functions from 120 files" while `parse.report.json` recorded `total_units: 5389`.

**(c) Unvalidated model output.** `report/generator.py` delegates the summary text to the model without validating the numbers it emits. Same-run contradictions: durations mis-rendered (`parse 10m 13s` against `parse.report.json`'s `duration_seconds: 10.22`; `3m 36s` against 3.6; `0m 4s` against 0.07); Stage-2 wording ("Verified in Stage 2: 3 findings" against the verify stage's adjudicated 1/4); and the Confirmed Vulnerabilities table — whose eligibility rule at `summary.txt:70` is `stage2_verdict is "confirmed" or "agreed"` — carrying rows labeled `static`/unverified.

**(d) Empty-case placeholders render literally.** After "No steps were skipped." the report renders `| {step} | {reason} |`; after "No false positives to report." it renders `| {name} | {verdict} | {verdict} | {one_sentence_reason} |` — the unfilled prompt tables, visibly in the artifact.

Missing URL/commit metadata alone is an honest absence and is out of scope here.

## Direction

- Fix the source-side population first: `units_analyzed` must not silently subtract errors (or the field must be named for what it is)
- Render count/duration/eligibility tables deterministically in `report/generator.py` from `pipeline_stats`/`findings`, and validate emitted numbers against them
- Remove the unsupported `{n} functions from {n} files` request or supply the fields
- Omit the empty-case table when the empty sentence is emitted; label incomplete rows as such rather than under "Confirmed"

Related (none covers these): #209/#347, #285/#376, #304/#403, #215/#436, #323/#449, #302/#401.

**Comment by gadievron** [comment]
PR #547 (CI 17/17 green, MERGEABLE) fixes this: the source re-sourced (units_analyzed from the analyze step report — the old formula was contaminated by Stage-2 verify errors), the numbers/tables server-rendered (one duration formatter, the Confirmed eligibility enforced, a Verified column shared with the disclosure banner, a strip-net for model duplicates), the phantom prompt requests removed. Leaving the merge to the maintainers.
