### PR TITLE
fix(report): SUMMARY_REPORT numbers and tables are server-rendered — the source re-sourced, the model-transcribed arithmetic retired (#535)

### LINKED ISSUE #535: SUMMARY_REPORT.md misstates its own run's numbers and violates its Confirmed-table eligibility — the source population feeds it wrong values and the prompt asks for fields that don't exist
SUMMARY_REPORT.md misstates its own run's numbers and violates its Confirmed-table eligibility — the source population feeds it wrong values and the prompt asks for fields that don't exist

From the 2026-09-07 monitored end-to-end run of the scan pipeline; re-derived from source at current master (ec6b063); pre-existing on master, not a regression from #526-#531.

## The claim

Three layers contribute, and a fix that only renders tables deterministically would preserve the misstatements:

**(a) Source-side population.** `core/reporter.py:770` computes `"units_analyzed": total_units - metrics.get("errors", 0)` — an errors-silent subtraction that produced `119` where the analyze stage recorded `analyzed: 120`, and that feeds every downstream count rendering.

**(b) The prompt asks for values the pipeline does not supply.** `report/prompts/summary.txt:32` renders "Parsed: {n} functions from {n} files" — no such fields exist in `pipeline_output`; the same run rendered "120 functions from 120 files" while `parse.report.json` recorded `total_units: 5389`.

**(c) Unvalidated model output.** `report/generator.py` delegates the summary text to the model without validating the numbers it emits. Same-run contradictions: durations mis-rendered (`parse 10m 13s` against `parse.report.json`'s `duration_seconds: 10.22`; `3m 36s` against 3.6; `0m 4s` against 0.07); Stage-2 wording ("Verified in Stage 2: 3 findings" against the verify stage's adjudicated 1/4); and the Confirmed Vulnerabilities table — whose eligibility rule at `summary.txt:70` is `stage2_verdict is "confirmed" or "agreed"` — carrying rows labeled `static`/unverified.

**(d) Empty-case placeholders render literally.** After "No steps were skipped." the report renders `| {step} | {reason} |`; after "No false positives to report." it renders `| {name} | {verdict} | {verdict} | {one_sentence_reason} |` — the unfilled prompt tables, visibly in the artifact.

Missing URL/commit metadata alone is an honest absence and is out of scope here.

## Direction

- Fix the source-side population first: `units_analyzed` must not silently subtract errors (or the field must be named for what it is)
- Render count/duration/eligibility tables deterministically in `report/generator.py` from `pipeline_stats`/`findings`, and validate emitted numbers against them
- Remove the unsupported `{n} functions from {n} files` request or supply the fields
- Omit the empty-case table when the empty sentence is emitted; label incomplete rows as such rather than under "Confirmed"

Related (none covers these): #209/#347, #285/#376, #304/#403, #215/#436, #323/#449, #302/#401.

### PR DESCRIPTION
**Pull request by gadievron**
## Summary

SUMMARY_REPORT.md's numbers and tables were model-transcribed JSON with arithmetic — and the model botched them (receipt, one run: `10.22s` rendered as `"10m 13s"`; "Verified in Stage 2: 3 findings" against an adjudicated 1/4; unverified rows in the Confirmed table; literal `{step}`/`{name}` placeholder tables; a "Parsed: 120 functions from 120 files" line against a parse total of 5389 — the prompt asked for fields that don't exist).

Four layers fixed:

**(a) Source re-sourced.** `units_analyzed` now comes from the analyze step report's own `analyzed` count — the old `total − metrics.errors` formula was exact on the analyze-only path but contaminated whenever verify ran (results_verified's recount buckets a Stage-2 verify ERROR on an already-analyzed unit into `errors`: 120 analyzed + 1 verify error reported 119). Fallback: the analyze-only formula when no verify ran; **omitted (present-only)** when verify ran without an analyze report. `parsed_units` forwarded from the parse step report. `stage1_errors` reads the real `error_count`/`verdicts.errors` keys. A $0 or sub-second step no longer vanishes from the tables.

**(b)(c) Server-rendered.** The statistics block (Parsed / In-scope / Analyzed / Adjudicated + the #302 same-model caveat, deterministic now), the Results / Per-Step Durations / Per-Step Costs / Confirmed / Not-Confirmed tables are rendered by the server in `report/generator.py`: present-only, one duration formatter that can't render 10.22s as 10m 13s, the Confirmed eligibility the prompt itself stated (`stage2_verdict ∈ {confirmed, agreed}`), the rest under a Not Confirmed table, and a `Verified` column with the same 4-tier dynamic-then-stage2 priority as the disclosure banner (the two documents agree for the same finding). A strip-net removes any model-emitted duplicate of a server-owned section (anchored, case-insensitive, numbering-tolerant); the blocks splice after the document's H1/metadata block.

**(d) Prompt cleaned.** The phantom requests are gone (functions-from-N-files, the CodeQL filter line, estimated-costs columns, the `Xm Ys` duration format, the placeholder exemplar tables); the model keeps the H1 metadata block, the coverage section (its own heading now — the strip-net would have deleted it under the old one), reachability warnings, skipped steps, incremental-scan notices, and methodology.

Test pins migrated, not deleted: the #215 severity cell and contiguity pins now target the renderer (the same guarantees, server-side); the #302 scope line and the new same-model-caveat pin likewise; the #319 Verified column survives as the shared `_verified_tier` helper.

Closes #535.

## Test plan

15 new tests in `tests/test_issue535_summary_server_numbers.py` (the reporter re-sourcing: the 120-not-119 regression, the analyze-only fallback, the verify-without-analyze omission, parsed_units, the $0-step, the verdicts.errors fallback; the renderer: the statistics lines, present-only, the duration formatter's boundary behavior, the Confirmed eligibility, no-placeholder, the strip-net's anchored/case/adjacent behavior, the placeholder strip, the costs table with no phantom columns) + the migrated #215/#302 pins.

## Verification evidence

| check | command | result |
|---|---|---|
| new + migrated tests | `pytest tests/test_issue535_summary_server_numbers.py tests/test_issue215_severity_field.py tests/test_issue302_stage2_scope_reporting.py -q` | all pass |
| full suite | `pytest tests/ -q` | 3930 passed, 2 failed — both pre-existing (SDK pin drift, verified on the pristine base) |
| static analysis | ruff / Semgrep / CodeQL | clean / 0 / the 3 hits in my two files pre-existing outside the touched hunks (same 3 as the prior-scan baseline) |

### CODE REVIEW

**Comment by gadievron** [comment]
**Gate-session receipt (the two-seat round: fable + astra; fable REFUTED as-shipped; the fold executed)**

**Re-derived independently:** the dead-arithmetic receipts verified plausible from the described artifacts; the suite 14/14 + the migrated pins 55/55; full suite 3744/0 fresh-venv; ruff clean. **Fable's blocker re-derived from source and CONFIRMED**: the splice guard `if m and m.start() > 0` **inverted the intent** — the canonical reply (H1 at offset 0) took the `elif` prepend branch, rendering the server tables **above the document title** (exactly the regression the PR's own comment says a review round fixed; no test observed position). Secondary confirmed: the no-heading path prepended the banners **twice** (the branch + the unconditional final prepend).

**Astra: REFUTED** ("decisive; correct numbers do not rescue an incorrectly assembled document") with the required splice semantics named: the H1-at-0 shape must be treated identically to a prefixed H1; the banners assembled in exactly one place; position-pinning tests for every shape.

**The fold (gate commit c0a00a6)**: the boundary normalized (every shape inserts AFTER the H1/metadata block — the inverted guard is gone); the banners prepend exactly once (the duplicate path removed); the position pins (title < tables < narrative; not-startswith-tables) + the banner-uniqueness source pin. Suite 16/16; full 3881/0.

**Receipt notes (astra's checklist):** the #319 verified-column pin's migration to the summary surface + the `_verified_tier` exercise named as the follow-up tightening; the units_analyzed absence has no zero-reading consumer (verified by fable); the strip-net's overmatch surfaces (the anchored/case/numbering-tolerance regex) — fable's enumeration stands as the documented limit with the anchored headings the net's own defense.

CI green on the folded head. Merge-ready.
